---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    run: nginx
spec:
  restartPolicy: Never
  containers:
  - name: nginx
    image: uditgaurav/3298r5972u:v1
    command: ['sh', '-c', 'echo The app is running! && sleep 3600']
    ports:
    - containerPort: 80
