name: Push

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Creating 3 Node GKE Cluster
      run: |
        chmod 755 ./build/github/stages/1-gke-setup/cluster-setup
        ./build/github/stages/1-gke-setup/cluster-setup
      env:
        SDK_TOKEN: ${{ secrets.SDK_TOKEN }}
        PROJECT_NAME: ${{ secrets.PROJECT_NAME }}

    - name: Creating nginx deployment application
      run: kubectl apply -f https://raw.githubusercontent.com/mayadata-io/chaos-ci-lib/master/app/nginx.yml

    - name: "[Prepare]: Setting up kubeconfig ENV for Github Chaos Action"
      run: echo ::set-env name=KUBE_CONFIG_DATA::$(base64 -w 0 ~/.kube/config)

    - name: Running pod delete chaos experiment
      uses: uditgaurav/kubernetes-chaos@master
      env:
        INSTALL_LITMUS: true
        APP_NS: default
        APP_LABEL: run=nginx
        APP_KIND: deployment
        TARGET_CONTAINER: nginx
        EXPERIMENT_NAME: all
        PARALLEL_EXECUTION: 2
        EXPERIMENT_IMAGE: litmuschaos/ansible-runner
        EXPERIMENT_IMAGE_TAG: latest    
        LITMUS_CLEANUP: true 

    - name: Deleting GKE Cluster
      run: |
        chmod 755 ./build/github/stages/2-gke-cleanup/cluster-cleanup
        ./build/github/stages/2-gke-cleanup/cluster-cleanup
      env:
        SDK_TOKEN: ${{ secrets.SDK_TOKEN }}
        PROJECT_NAME: ${{ secrets.PROJECT_NAME }}
