name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Creating Gloud Cluster
      run: |
        - chmod 755 ./build/gitlab/stages/1-gke-setup/cluster-setup
        - ./build/gitlab/stages/1-gke-setup/cluster-setup
      env:
        SDK_TOKEN: ${{ secrets.SDK_TOKEN }}
        PROJECT_NAME: ${{ secrets.PROJECT_NAME }} 
           
    - name: Running pod delete chaos experiment
      uses: uditgaurav/kubernetes-chaos@master
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
        ##if litmus is not installed
#         INSTALL_LITMUS: true
        ##Give application info under chaos
        ##Currently supporting "deployment" applications.
        APP_NS: default
        APP_LABEL: run=nginx
        EXPERIMENT_NAME: pod-delete
        TOTAL_CHAOS_DURATION: 30
        CHAOS_INTERVAL: 10
        FORCE: false
        ##Select true if you want to uninstall litmus after chaos
#         LITMUS_CLEANUP: true

    - name: Deleting Gloud Cluster
      run: |
        - chmod 755 ./build/gitlab/stages/2-gke-cleanup/cluster-cleanup
        - ./build/gitlab/stages/2-gke-cleanup/cluster-cleanup
      env:
        SDK_TOKEN: ${{ secrets.SDK_TOKEN }}
        PROJECT_NAME: ${{ secrets.PROJECT_NAME }}



